import dotenv from 'dotenv';
import { connectDB } from '../config/database.js';
import { Category, SubCategory, Product } from '../models/index.js';

dotenv.config();

const products = [
  "Acetic Acid Glacial 99.5% for Synthesis",
  "Acetic Acid Glacial 99.8-100.5% AR/ACS & P Test",
  "Acetone 99.5% AR/ACS",
  "Acetonitrile 99.5% AR/ACS",
  "Acetonitrile 99.9% for HPLC & Spectroscopy",
  "Acetonitrile 99.9% for HPLC Gradient Grade",
  "Acetyl Chloride 98% for Synthesis",
  "Acetyl Choline Chloride 99% AR",
  "Acrylic Acid 99% for Synthesis",
  "Agar Powder for Bacteriology",
  "Aluminum Metal Fine Powder 99%",
  "Aluminum Ammonium Sulphate 12 Hydrate 99.5% AR",
  "Aluminum Chloride Anhydrous 98% for Synthesis",
  "Aluminum Chloride Hexahydrate 99% AR",
  "Aluminum Nitrate Nonahydrate 98.5% AR/ACS",
  "Aluminum Oxide Neutral pH 6.5-7.5",
  "Aluminum Oxide 99.9% AR",
  "Aluminum Sulphate Hexadecahydrate 99.5% AR/ACS",
  "p-Amino Phenol Extra Pure",
  "Ammonium Acetate (Crystals) 98% AR/ACS",
  "Ammonium Benzoate 98% Purified",
  "Ammonium Bromide 99.5% AR/ACS",
  "Ammonium Carbonate 31% AR/ACS",
  "Ammonium Chloride 99.8% AR",
  "tri-Ammonium Citrate 98.5% AR",
  "Ammonium Ferrous Sulphate Hexahydrate 99% AR",
  "Ammonium Fluoride 98% AR",
  "Ammonium Formate 98% AR",
  "Ammonium Molybdate Tetrahydrate 99% AR",
  "Ammonium Oxalate Monohydrate 99.5% AR",
  "Ammonium Purpurate 85% AR/ACS",
  "Ammonium Sulphate 99.5% AR/ACS",
  "Ammonium-(+)-Tartrate 99% AR",
  "Ammonium Thiocyanate 99% AR",
  "Aniline 99% for Synthesis",
  "Aniline Hydrochloride 99-100.5% for Synthesis",
  "Aniline Sulphate 99% for Synthesis",
  "L-Ascorbic Acid 99.7% for Biochemistry AR",
  "Barium Carbonate 99% AR/ACS",
  "Barium Chloride Dihydrate Crystals 99% Pure",
  "Barium Chloride Dihydrate 99% AR/ACS",
  "Barium Hydroxide Octahydrate 98% AR",
  "Barium Nitrate 99.5% AR/ACS",
  "Barium Sulphate Precipitated 95%",
  "Barium Sulphate Precipitated 97.5% AR",
  "Beeswax White for Histology",
  "Beeswax Yellow for Histology",
  "Benedict's Reagent Qualitative",
  "Benzaldehyde 99% AR",
  "Benzalkonium Chloride 50% Solution",
  "Benzamide 98.5% for Synthesis",
  "Benzanilide 99% for Synthesis",
  "Benzoic Acid 99.9% AR",
  "Benzyl Alcohol 99% AR/ACS",
  "Benzyl Benzoate 98%",
  "Bismuth Oxide 99%",
  "Bismuth Phosphate 98%",
  "Bismuth Subnitrate 71% AR",
  "Bismuth Sulphate 90%",
  "Borax Decahydrate 99.5% AR/ACS",
  "Boric Acid Crystals 99.5% AR",
  "Brilliant Green Indicator 95% for Microscopy",
  "Bromine Water",
  "Bromoform 99% Special Grade",
  "1-Butane Sulphonic Acid Sodium Salt Anhydrous 99% AR",
  "n-Butanol 99.5% AR",
  "2-Butanol 99.5% AR",
  "Tert-Butanol 99.5% AR",
  "Butylated Hydroxytoluene (BHT) 99%",
  "Cadmium Acetate Dihydrate 99% AR",
  "Cadmium Carbonate 62-66%",
  "Cadmium Chloride Monohydrate 99% AR",
  "Cadmium Iodide 99%",
  "Cadmium Oxide 99.5%",
  "Cadmium Phosphate 98%",
  "Cadmium Sulphate 99.99% AR",
  "Caffeine Anhydrous 98% Pure",
  "Calamine 98% Purified",
  "Calcium Acetate 99% AR/ACS for Soil Test",
  "Calcium Carbide",
  "Calcium Carbonate Precipitated 99.5% AR",
  "Calcium Chloride Dihydrate 99% AR",
  "Calcium Hydroxide 96% AR",
  "Calcium Lactate 98% for Soil Test",
  "Calcium Nitrate Tetrahydrate 99%",
  "Calcium Oxide (Lumps) 97.5%",
  "Calcium Oxide Anhydrous Powder 96%",
  "di-Calcium Phosphate Dihydrate 98%",
  "tri-Calcium Phosphate 90%",
  "Calcium Sulphate Anhydrous 97%",
  "Calcium Sulphate Dihydrate 99%",
  "Calcium Tungstate 99.5%",
  "Camphor MAR 97%",
  "Carbopol Fuchsin Powder for Microscopy",
  "Carbon Tetrachloride 99.5% for Synthesis",
  "Carbon Tetrachloride 99.9% AR",
  "Carbopol 934",
  "Carboxymethyl Cellulose Sodium Salt",
  "Casein from Bovine Milk",
  "Cellulose Powder",
  "Cetostearyl Alcohol 90% AR",
  "Cetrimide 96-101%",
  "Cetyl Alcohol 95% Pure",
  "Charcoal Activated AR",
  "Chloroacetic Acid Mono 99.5% AR",
  "Chlorobenzene Mono 99.5% AR",
  "Chloroform 99% AR",
  "Cholesterol 95% Purified",
  "Chromium (III) Chloride Hexahydrate 96%",
  "Chromium (III) Sulphate Basic",
  "Chromium Trioxide 99% AR",
  "Cinnamic Acid 99.5% AR",
  "Citric Acid Anhydrous 99.5% AR",
  "Citric Acid Monohydrate 99.5% AR",
  "Cobalt AAS Solution 1000 ppm",
  "Cobaltous Acetate Tetrahydrate 99-102% AR/ACS",
  "Cobaltous Carbonate 45-50%",
  "Cobaltous Chloride Hexahydrate 99% AR",
  "Cobaltous Nitrate Hexahydrate 99% AR/ACS",
  "Cobalt (II & III) Oxide 70%",
  "Cobaltous Sulphate Heptahydrate 99% AR",
  "Congo Red Indicator pH 3.0-5.2",
  "Copper Metal Powder Electrolytic 99.5%",
  "Copper Metal Powder Fine 99.7% AR",
  "Copper (II) Acetate Monohydrate 99% AR",
  "Copper (II) Carbonate 54-57%",
  "Copper (II) Chloride Dihydrate 99% AR",
  "Copper (II) Nitrate Trihydrate 99.5% AR/ACS",
  "Copper (II) Oxide Powder 99% AR/ACS",
  "Copper (II) Sulphate Anhydrous 98%",
  "Copper (II) Sulphate Pentahydrate 99.5% AR/ACS",
  "Cotton Blue for Microscopy",
  "Crystal Violet 90% for Microscopy",
  "Cuprous Chloride 97% AR/ACS",
  "Cuprous Oxide Red 94%",
  "Cyclohexane 99.5% AR",
  "Cyclohexanone 99.5% AR",
  "L-Cystine 99% for Biochemistry",
  "Dextrose Anhydrous AR",
  "1,2-Dichloro Ethane 99% for Synthesis",
  "Dichloro Methane Pure 99% for Synthesis",
  "Dichloro Methane 99.5% AR",
  "2,6-Dichloro Phenol Indophenol Sodium Salt 98% AR",
  "Diethanolamine 98% for Synthesis",
  "Diethyl Ether 99% AR",
  "Dimethyl Glyoxime 99% AR/ACS",
  "Diphenylamine 99% AR/ACS",
  "Diphenyl Carbazone-Bromophenol Blue",
  "Eosin Yellow Indicator 88% for Microscopy",
  "Ferric Chloride Anhydrous 98%",
  "Ferric Oxide Red 95%",
  "Ferric Sulphate Hydrate 20.5%",
  "Ferrous Oxalate Dihydrate 99%",
  "Ferrous Sulphate Hydrate 86.89%",
  "Formic Acid 98-100%",
  "D-(-)-Fructose",
  "Fuchsin Acid 60% for Microscopy",
  "Fuchsin Basic 88% for Microscopy",
  "Fumaric Acid 99% for Synthesis",
  "D-(+)-Galactose",
  "Gallic Acid Monohydrate 98%",
  "Gelatin Powder for Bacteriology",
  "Gentian Violet 90% for Microscopy",
  "Giemsa's Stain for Microscopy",
  "Giemsa's Stain Solution for Microscopy",
  "Glass Wool",
  "L-Glutamic Acid 99% for Biochemistry",
  "Gram's Iodine Solution",
  "Hematoxylin Monohydrate for Microscopy",
  "1-Hexane Sulfonic Acid Sodium Salt 99% AR for HPLC",
  "Hydrazine Hydrate 99% AR",
  "Hydrofluoric Acid 48% AR",
  "Hydroquinone 99.5% AR",
  "Immersion Oil for Microscopy",
  "Iodine Resublimed 99.8% AR",
  "Iron Metal Powder Electrolytic 300 Mesh 95%",
  "Kaolin Light",
  "Kovac's Indole Reagent",
  "Lactic Acid 88% AR",
  "Lactophenol for Microscopy",
  "Lactose Monohydrate for Bacteriology AR",
  "Lanolin Anhydrous",
  "Lead (II) Acetate Trihydrate 99.5% AR/ACS",
  "Lead (II) Carbonate 99% AR/ACS",
  "Lead Nitrate 99.5% AR/ACS",
  "Lead Oxide Red 85%",
  "Lead Sulphate 98%",
  "Leishman's Stain for Microscopy",
  "Leishman's Stain Solution",
  "Lithium Acetate 99%",
  "Lithium Carbonate 99% AR",
  "Lithium Chloride 99% AR",
  "Lithium Hydroxide Monohydrate 99% AR/ACS",
  "Lithium Sulphate Monohydrate 99% AR/ACS",
  "Lugol's Iodine 5% Solution",
  "Magnesium Acetate Tetrahydrate 99% AR/ACS",
  "Magnesium Metal Ribbon 99.5%",
  "Magnesium Carbonate Basic Light 40%",
  "Magnesium Chloride Hexahydrate 99% AR",
  "Magnesium Citrate Hydrate 97%",
  "Magnesium Hydroxide 95%",
  "Magnesium Nitrate Hexahydrate 99% AR/ACS",
  "Magnesium Oxide Light 98% AR/ACS",
  "Magnesium Stearate 3.8-5%",
  "Magnesium Sulphate Heptahydrate 99.5% AR/ACS",
  "Magnesium II 95% AR",
  "Malachite Green 90% for Microscopy",
  "Maleic Acid 99.5% AR",
  "D-(+)-Maltose Monohydrate Crystal",
  "Phenolphthalein TS",
  "Phenol Red 98% AR",
  "Phenyl Acetate 98%",
  "Phenyl Hydrazine AR",
  "Phenyl Hydrazine Hydrochloride 99% AR",
  "ortho-Phosphoric Acid 85–88% AR",
  "Phthalic Acid 99.5% AR",
  "Picric Acid 99.8% AR",
  "Polyethylene Glycol 400",
  "Polyethylene Glycol 4000",
  "Polyvinyl Alcohol Cold 99%",
  "Potassium Acetate 99% AR/ACS",
  "Potassium Bicarbonate 99%",
  "Potassium Bromide 99.5% AR/ACS",
  "Potassium Carbonate Anhydrous 99.9% AR/ACS",
  "Potassium Chloride 99.5% AR",
  "Potassium Chromate 99–99.5%",
  "Tri-Potassium Citrate 99% AR",
  "Potassium Dichromate 99.9% AR",
  "Potassium Dihydrogen Ortho Phosphate 99.5–100.5% AR",
  "Potassium Ferricyanide 99% AR/ACS",
  "Potassium Ferrocyanide 99% AR/ACS",
  "Potassium Fluoride Anhydrous 99% AR",
  "Potassium Hydrogen Phthalate 99.9% AR",
  "Potassium Hydrogen Sulphate 99% AR",
  "Potassium Hydroxide Pellets 85% AR/Purified",
  "Potassium Iodate 99.9% AR",
  "Potassium Iodide 99.8% AR/ACS",
  "Potassium Metabisulfite 97% AR",
  "Potassium Nitrate 99.5% AR",
  "Potassium Oxalate 99.5% AR/ACS",
  "Potassium Permanganate 99–99.5% AR",
  "Potassium Persulfate 99% AR",
  "Potassium Sodium-(+)-Tartrate 99% AR/ACS",
  "Potassium Sorbate 99%",
  "Potassium Sulfate 99.5% AR/ACS",
  "Potassium Thiocyanate 99% AR",
  "2-Propanol 99.5–99.8% AR",
  "Pyridine 99.5% AR",
  "Saccharin Sodium Dihydrate 98%",
  "Safranin O for Microscopy",
  "Salicylaldehyde 99%",
  "Salicylic Acid 99% AR",
  "Silica Gel Blue",
  "Silica Gel 60-120 Mesh",
  "Silica Gel 100-200 Mesh",
  "Silica Gel GF 254",
  "Silicon Carbide 220–400 Mesh",
  "Silicon Oil",
  "Silver Metal Powder 99.9%",
  "Silver Chloride 99% AR",
  "Silver Nitrate 99.9% AR/ACS",
  "Silver Oxide 99% AR",
  "Silver Sulphate 99% AR/ACS",
  "Skim Milk Powder for Microbiology",
  "Sodium Metal / Granules 99% AR",
  "Sodium Acetate Anhydrous 99% AR/ACS",
  "Sodium Acetate Trihydrate 99.5% AR",
  "Sodium Alginate",
  "Sodium Azide 99.5% AR",
  "Sodium Benzoate 99.5% AR",
  "Sodium Bisulphite 58.5%",
  "Sodium Carbonate Anhydrous 99.5% AR",
  "Sodium Carbonate Monohydrate 99%",
  "Sodium Chloride 99.5–99.9% AR/ACS",
  "Sodium Chromate Tetrahydrate 99% AR",
  "Tri-Sodium Citrate Dihydrate 99% AR/ACS",
  "Sodium Cobaltinitrite 95% AR",
  "Sodium Cyanide 95%",
  "Sodium Dichromate Dihydrate 99.5% AR",
  "Sodium Dihydrogen Phosphate Dihydrate 98%",
  "Sodium Dithionite 80%",
  "Sodium Fluoride 99% AR",
  "Sodium Formate 99% AR/ACS",
  "Sodium Hydrogen Carbonate 99.7% AR",
  "Di-Sodium Hydrogen Phosphate Anhydrous 99% AR",
  "Sodium Hydrogen Sulphate Monohydrate 99% AR",
  "Sodium Hydroxide Pellets 98% AR",
  "Sodium Iodate AR",
  "Sodium Iodide 99.5–100.5% AR/ACS",
  "Sodium Lactate 60% Solution",
  "Sodium Lauryl Sulphate 99% AR (for SDS-PAGE)",
  "Sodium Metabisulphite 98% AR/ACS",
  "Sodium Metasilicate Nonahydrate 95%",
  "Sodium Molybdate 99% AR",
  "Sodium Nitrate 98–99.5% AR/ACS",
  "Sodium Nitrite 98% AR",
  "Sodium Nitroprusside 99% AR/ACS",
  "Sodium Oxalate 99.9% AR",
  "Sodium Perchlorate Monohydrate 98% AR",
  "Sodium Peroxide 95% AR/ACS",
  "Sodium Persulphate 95%",
  "Sodium Salicylate 99–99.5% AR",
  "Sodium Sulphate Anhydrous 99.5% AR/ACS",
  "Sodium Sulphide Flakes 55–60%",
  "Sodium Sulphite Anhydrous 96%",
  "di-Sodium Tartrate 99% AR",
  "Sodium Thiocyanate 99% AR/ACS",
  "Sodium Thiosulphate Anhydrous 98% AR",
  "Sodium Thiosulphate Pentahydrate 99.5% AR/ACS",
  "Sodium Tungstate Hydrated 98–99% AR",
  "Sodium-meta-Vanadate 98%",
  "Sorbic Acid 98.5%",
  "D-Sorbitol 98% for Biochemistry",
  "Stannic Chloride Pentahydrate 97.5%",
  "Stannous Chloride Dihydrate 98% AR/ACS",
  "Starch Corn",
  "Starch Soluble",
  "Stearic Acid 98% for Synthesis",
  "Strontium Chloride 99% AR/ACS",
  "Strontium Nitrate 99% AR/ACS",
  "Strontium Sulphate 98%",
  "Sucrose 99.5% AR/ACS",
  "Sudan III 85% for Microscopy",
  "Sulphamic Acid 99.5% AR",
  "Sulphanilic Acid 98–99% AR",
  "Sulphuric Acid 98% AR",
  "Tannic Acid 90% AR",
  "L-(+)-Tartaric Acid 99.5% AR",
  "Tetrabutyl Ammonium Hydrogen Sulphate 0.98",
  "Tetrabutyl Ammonium Hydroxide 0.1 N",
  "Tetrabutyl Ammonium Iodide 99% AR",
  "Tetrahydrofuran 99.5% AR",
  "Thioglycollic Acid 80%",
  "Thiourea 99% AR",
  "Thymol Crystals 99.5% AR",
  "Tin Metal Powder 99.5% AR",
  "Titanium Dioxide 99% AR",
  "Toluene 99.5% AR",
  "Trichloroacetic Acid 99.5% AR",
  "Triethanolamine 99% AR",
  "Triethylamine 99.5% AR",
  "Trifluoroacetic Acid 98%",
  "Tween 20",
  "Tween 80",
  "L-Tyrosine 98.5% for Biochemistry",
  "Urea Crystal Pure 99% for Biochemistry",
  "Urea 99–101% AR",
  "Uric Acid 99% AR",
  "Vanillin 99% AR",
  "W.B.C. Diluting Fluid (Truck's)",
  "Xylene 99.8% AR",
  "Zinc Metal Dust 99.5% AR",
  "Zinc Metal Granular 99.7% AR",
  "Zinc Metal Powder 99.9% AR",
  "Zinc Acetate 99.5% AR",
  "Zinc Carbonate Basic 58%",
  "Zinc Chloride (Dry) 98% AR",
  "Zinc Nitrate Hexahydrate 99% AR",
  "Zinc Oxide 99–100.5% AR",
  "Zinc Stearate Pure",
  "Zinc Sulphate Heptahydrate 99.5% AR"
];

const addChemicals = async () => {
  try {
    await connectDB();

    // Find category
    const category = await Category.findOne({
      where: { name: 'كيماويات وأوساط زراعية' }
    });

    if (!category) {
      console.error('❌ Category not found');
      process.exit(1);
    }

    console.log(`✅ Found category: ${category.getDataValue('name')} (ID: ${category.getDataValue('id')})`);

    // Find or create subcategory
    let subCategory = await SubCategory.findOne({
      where: { 
        categoryId: category.getDataValue('id'),
        name: 'مواد كيميائية'
      }
    });

    if (!subCategory) {
      subCategory = await SubCategory.create({
        categoryId: category.getDataValue('id'),
        name: 'مواد كيميائية'
      });
      await subCategory.reload();
      console.log('✅ Created subcategory: مواد كيميائية');
    } else {
      console.log(`✅ Found subcategory: ${subCategory.getDataValue('name')} (ID: ${subCategory.getDataValue('id')})`);
    }

    const subCategoryId = subCategory.getDataValue('id');

    // Add products
    let addedCount = 0;
    for (const productName of products) {
      try {
        await Product.create({
          subCategoryId: subCategoryId,
          name: productName,
          description: productName,
          specifications: '',
          price: 0,
          image: '/images/placeholder.jpg'
        });
        addedCount++;
        if (addedCount % 50 === 0) {
          console.log(`✅ Added ${addedCount} products...`);
        }
      } catch (error: any) {
        console.error(`❌ Error adding ${productName}:`, error.message);
      }
    }

    console.log(`\n🎉 Successfully added ${addedCount} out of ${products.length} products!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
};

addChemicals();
